### ISSUE TITLE
Client hangs for a while on load if GitHub is down

### ISSUE THREAD

**Issue by xJon** [eve0415/IFPatcher#13]
(Don't ask me how I know)
```
[00:25:16] [Client thread/INFO]: Patching CustomConfiguration from IF
[00:25:16] [Client thread/INFO]: Patched Custom Configuration
[00:25:16] [Client thread/INFO]: PatchCustomConfiguration succeeded
[00:25:39] [Client thread/INFO]: [com.buuz135.industrial.proxy.CommonProxy:preInit:198]: java.io.IOException: Server returned HTTP response code: 500 for URL: https://raw.githubusercontent.com/Buuz135/Industrial-Foregoing/master/contributors.json
[00:25:39] [Client thread/INFO]: [com.buuz135.industrial.proxy.CommonProxy:preInit:198]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[00:25:39] [Client thread/INFO]: [com.buuz135.industrial.proxy.CommonProxy:preInit:198]:     at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[00:25:39] [Client thread/INFO]: [com.buuz135.industrial.proxy.CommonProxy:preInit:198]:     at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
...
```
Would be nice to resolve that.

**Comment by Pyker** [comment]
The URL should probably also be updated to reflect the new repo path: https://raw.githubusercontent.com/InnovativeOnlineIndustries/Industrial-Foregoing/master/contributors.json (https://github.com/Buuz135/Industrial-Foregoing redirects to that, meaning the repo was moved)
